# Okno
background         #0a0f18
foreground         #dce4f0
background_opacity 0.1
background_blur    50
window_padding_width 15
confirm_os_window_close 0

# Ramki
window_margin_width 12
window_border_width 1pt
active_border_color #89b4fa
inactive_border_color #1c2541
draw_minimal_borders yes

hide_window_decorations yes

# Kursor
cursor             #89b4fa
cursor_text_color  #0a0f18
cursor_shape       beam

# Kolory
color0 #1e1e2e
color8 #585b70
color1 #f38ba8
color9 #f38ba8
color2 #a6e3a1
color10 #a6e3a1
color3 #f9e2af
color11 #f9e2af
color4 #89b4fa
color12 #89b4fa
color5 #f5c2e7
color13 #f5c2e7
color6 #94e2d5
color14 #94e2d5
color7 #bac2de
color15 #a6adc8

linux_display_server wayland
shell_integration no-rc
repaint_delay 10
input_delay 3
sync_to_monitor yes